name: PR check
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      TEST_PROVIDER_BASE_URL: http://127.0.0.1:5050/
    services:
      devnet:
        image: janek2601/starknet-devnet-patched
        ports:
          - 5050:5050

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
